version: '3'

services:

  db:
    image: easyengine/mariadb
    restart: always
    volumes:
      - "./app/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - site-network
    
  php:
    image: easyengine/php
    depends_on:
      - db
    restart: always
    volumes:
      - "./app/src:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    networks:
      - site-network
    
  nginx:
    image: easyengine/nginx
    depends_on:
      - php
    restart: always
    labels: 
      - "traefik.enable=true"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
      - "traefik.secure.port=443"
      - "traefik.secure.protocol=https"
      - "traefik.docker.network=site-network"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=HostRegexp:{subdomain:.+}.${VIRTUAL_HOST},${VIRTUAL_HOST}"
    volumes:
      - "./app/src:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./logs/nginx:/var/log/nginx"
    networks:
      - site-network
    
  mail:
    image: easyengine/mail
    restart: always
    command: ["-invite-jim=false"]
    labels: 
      - "traefik.port=8025"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST};PathPrefixStrip:/ee-admin/mailhog/"
    networks:
      - site-network
    
  phpmyadmin:
    image: easyengine/phpmyadmin
    restart: always
    labels: 
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST};PathPrefixStrip:/ee-admin/pma/"
    environment:
      - PMA_ABSOLUTE_URI=http://${VIRTUAL_HOST}/ee-admin/pma/
    networks:
      - site-network
    

networks:
  site-network:
    external:
      name: ${VIRTUAL_HOST}
