defaultEntryPoints = ["http", "https"]

InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
[retry]


[api]
entryPoint = "traefik"
dashboard = true
debug = true

[docker]
domain = "docker.local"
watch = true
exposedByDefault = false

[file]
directory = "/etc/traefik/endpoints/"
watch = true

